<?php

$GLOBALS['SQLITE_USER'] = '<SQLITE_USER>';
$GLOBALS['SQLITE_PASS'] = '<SQLITE_PASS>';
$GLOBALS['SQLITE_LOCATION'] = '<DBLOCATION>/<DBNAME>.db';
$GLOBALS['MYSQL_USER'] = '<MYSQL_USER>';
$GLOBALS['MYSQL_PASS'] = '<MYSQL_PASS>';
$GLOBALS['MYSQL_HOST'] = 'localhost';
$GLOBALS['SQLSVR_USER'] = '<SQLSVR_USER>';
$GLOBALS['SQLSVR_PASS'] = '<SQLSVR_PASS>';
$GLOBALS['SQLSVR_HOST'] = 'localhost';

?>
