<?php

$GLOBALS['LOG_PATH'] = '<PATH_TO_LOGFILE>';
$GLOBALS['SQLITE_USER'] = '<SQLITE_USER>';
$GLOBALS['SQLITE_PASS'] = '<SQLITE_PASS>';
$GLOBALS['SQLITE_LOCATION'] = '<DBLOCATION>/<DBNAME>.db';
$GLOBALS['MYSQL_USER'] = '<MYSQL_USER>';
$GLOBALS['MYSQL_PASS'] = '<MYSQL_PASS>';
$GLOBALS['MYSQL_HOST'] = 'localhost';
$GLOBALS['MYSQL_DATABASE'] = '<MYSQL_DATABASE>';
$GLOBALS['SQLSRV_USER'] = '<SQLSRV_USER>';
$GLOBALS['SQLSRV_PASS'] = '<SQLSRV_PASS>';
$GLOBALS['SQLSRV_DSN'] = 'sqlsrv:server = tcp:<HOST>,<PORT>; Database = <DB>';
$GLOBALS['SQLSRV_DATABASE'] = '<SQLSRV_DATABASE>';

?>
